// <auto-generated />
using System;
using IndigoSoftTest.BusinessLogic.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IndigoSoftTest.BusinessLogic.Migrations
{
    [DbContext(typeof(IndigoSoftTestDbContext))]
    [Migration("20250429123933_AddUserIps")]
    partial class AddUserIps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IndigoSoftTest.BusinessLogic.Entities.UserIp", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<int>("IpAddressVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastConnectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("IpAddress");

                    b.ToTable("UserIps");
                });
#pragma warning restore 612, 618
        }
    }
}
