CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "UserIps" (
    "UserId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IpAddress" text,
    "IpAddressVersion" integer NOT NULL,
    "LastConnectionDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserIps" PRIMARY KEY ("UserId")
);

CREATE INDEX "IX_UserIps_IpAddress" ON "UserIps" ("IpAddress");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250429123933_AddUserIps', '9.0.4');

COMMIT;

